version: "3.2"
services:
  database:
    container_name: wanted-preonboarding-database
    image: mysql
    environment:
      MYSQL_DATABASE: preonboarding_db
      MYSQL_USER: wanted
      MYSQL_PASSWORD: fu0a930a9u
      MYSQL_ROOT_PASSWORD: 1f9af389wko
    volumes:
      - ./db/data:/var/lib/mysql:rw
    ports:
      - "3306:3306"


  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://wanted-preonboarding-database:3306/preonboarding_db
      SPRING_DATASOURCE_USERNAME: wanted
      SPRING_DATASOURCE_PASSWORD: fu0a930a9u
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: always
